### ISSUE TITLE
Koyo Protocol docs

### ISSUE THREAD

**Issue by GhostofGoes** [SimplyAutomationized/PythonKoyo#2]
How were the binary strings to send determined? Did you just fuzz with wireshark, or is there some documentation available for reference?

**Comment by SimplyAutomationized** [comment]
I wasn't able to find any docs on it so I did it with Wireshark.  Sniffing between DirectSoft-> PLC and their Network Tool -> PLC.

**Comment by GhostofGoes** [comment]
Yeah, figured as much. Been doing the same, figured I'd check and see if there was an easier way.

Thanks!
